### PR TITLE
Check answer upon pressing the Solve button

### PR DESCRIPTION
**Pull request by JapanYoshi**
This allows the host to not have to note down the questions elsewhere beforehand, and in fact, host the show without knowing the answer himself.

### CODE REVIEW

**Comment by TimTree** [comment]
Hi JapanYoshi! Thank you for taking your time to write this pull request. Never expected to see one of these on Wheel of Fortune for PowerPoint!

Adding the ability to host a Wheel of Fortune game without knowing the solutions is an excellent idea, and I like the way you implemented it. That said, it adds an additional click for hosts who know the puzzle, which I assume will be the case for the majority of hosts.

What I plan to do is add a new gameplay setting, **Solve Button**, with the following options:

- **reveal puzzle** (default) - Reveal the puzzle when clicking Solve
- **check answer** - An input box appears when clicking Solve, prompting the host to type the player's answer to check it. 

Due to how I handle GitHub repos for PowerPoint projects, I do not merge pull requests. However, know that I approve of your idea, will likely use a good portion of your code, and will credit you in the About/Credits slide and the update notes once this feature is released.

I will keep this PR open until I implement the feature and may add comments here if updates arise.

**Comment by JapanYoshi** [comment]
Thank you for your comments!

I agree that, if the host has already noted down the correct answers elsewhere, the extra dialog is kind of a bother. For that reason, I've also added the "/reveal" command to skip answer-checking, and defaulted the input box's contents to that.

Regardless, I do think your idea of adding a dedicated setting for it is great, and in fact the ideal option here.

As a side-note, may I request that the font be defined through Powerpoint's inbuilt theme settings? That would make it easier for those who want to customize the font used in the spreadsheet.

image
Before:
image
After (Franklin Gothic for board, Calibri for other text)
image

**Comment by TimTree** [comment]
Thanks for pointing out the Themes feature in PowerPoint. I have not touched that feature, and it does seem like the right way to go with font customization, considering everything is a single font now.

I will also explore Themes functionality for the next release.

**Comment by TimTree** [comment]
Feature was implemented in version 6.4 with the following adjustments:
- Runs if the new setting, Solve Button, is set to **verify**.
- Used a dedicated function to handle verify solve functionality
- The default input is the puzzle as currently on the board, with underscores for the unrevealed letters.
- The user answer is trimmed of trailing spaces before getting checked.
- Automatically reveal the puzzle if the puzzle is blank or all letters have been revealed in the puzzle
- Removed the /giveup option as clicking Cancel, closing the input box, or submitting the default input are equivalent and faster ways of giving up

Thank you for the PR!

**Pull request closed without merging**
